import type { Metadata } from "next";
import { Andika, Poppins, Nunito } from "next/font/google";
import { ThemeProvider as NextJSThemeProvider } from "next-themes";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

const andika = Andika({
  variable: "--font-andika",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Skyeris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${andika.variable} ${poppins.variable} ${nunito.variable} antialiased`}
      >
        <NextJSThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Providers>
            <Header/>
            <main className="min-h-screen container mx-auto px-4 py-8">
              {children}
            </main>
          </Providers>
          <Footer/>
        </NextJSThemeProvider>
      </body>
    </html>
  );
}
